### ISSUE TITLE
SSH Port

### ISSUE THREAD

**Issue by acvander** [titanium-codes/cibu#4]
Is it possible to add a feature that would allow for a user to specify the ssh port to be used for the commands? Since using a non-standard ssh port increases security, this would permit users to utilize this program with non-standard ports.

**Comment by rakshazi** [comment]
Good idea!
Could you send a PR for it, please?

**Comment by rakshazi** [comment]
Did it myself, the var called `TARGET_PORT`, default is 22

**Comment by acvander** [comment]
Thanks for the addition.

**Comment by rakshazi** [comment]
You are welcome :)
